---
title: "CABG sex"
author: "Joonatan Palmu"
date: "`r format(Sys.time(), '%d.%m.%Y')`"
---

```{r options, include=FALSE}
knitr::opts_chunk$set(message = FALSE, cache = FALSE, results='asis', warning=FALSE)
now <- format(Sys.time(), '%Y%m%d-%H%M%S')
```

# Libraries

<details>
  <summary>Libraries</summary>

```{r libraries, results = 'hide'}
library(packrat)
library(magrittr)
library(tibble)
library(readr)
library(dplyr)
library(knitr)
library(purrr)
library(tidyr)
```

# Import data

```{r read data}
dset.interaction <- read_csv("interaction/results_CABG_20210512.out") 
dset.males <- read_csv("subsample/results_CABG_20210519_nofemales=1_nomales=0.out")
dset.females <- read_csv("subsample/results_CABG_20210519_nofemales=0_nomales=1.out")
```

# List data

```{r list data}
dset <- list(interaction = dset.interaction %>%
                 filter(is.na(lag_hr)) %>%
                 select(prior, outcome, sexprior_pval),
             females = dset.females %>%
                 mutate(female_prior_hr_ci = sprintf("%.1f (%.1f-%.1f)",
                                                     prior_hr,
                                                     prior_ci_lower,
                                                     prior_ci_upper)) %>%
                 select(prior,
                        outcome,
                        female_nevents = nevents,
                        female_nindivs_prior_outcome = nindivs_prior_outcome,
                        female_prior_hr = prior_hr,
                        female_prior_hr_ci,
                        female_prior_pval = prior_pval),
             males = dset.males %>%
                 mutate(male_prior_hr_ci = sprintf("%.1f (%.1f-%.1f)",
                                                   prior_hr,
                                                   prior_ci_lower,
                                                   prior_ci_upper)) %>%
                 select(prior,
                        outcome,
                        male_nevents = nevents,
                        male_nindivs_prior_outcome = nindivs_prior_outcome,
                        male_prior_hr = prior_hr,
                        male_prior_hr_ci,
                        male_prior_pval = prior_pval))
```

# Characteristics

```{r number of males}
dset.males %>% select(prior, outcome, nobservations, nevents, nindivs_prior_outcome)
```

```{r number of females}
dset.females %>% filter(outcome != "I9_CABG") %>% select(prior, outcome, nobservations, nevents, nindivs_prior_outcome)
```


# Results

- erikseen CABG prior ja CABG outcome (eli 2 taulukkoa).
- sarakkeet 1) nais-HR+p-arvo; 2) mies-hr+p-arvo ja 3) interaktio-p-arvo. 

## Prior CABG

```{r prior cabg}
dset %>%
    map(~filter(., prior == "I9_CABG")) %>%
    map(~select(., -prior)) %>%
    reduce(left_join, by = "outcome") %>%
    arrange(sexprior_pval) %>%
    filter(sexprior_pval < 0.05/1384,
           female_prior_hr > 2*male_prior_hr | male_prior_hr > 2*female_prior_hr) %>%
    mutate_at(vars(ends_with("pval")), ~sprintf("%.1E", .x)) %>%
    mutate(female_nevents = sprintf("%s/%s", female_nindivs_prior_outcome, female_nevents),
           male_nevents = sprintf("%s/%s", male_nindivs_prior_outcome, male_nevents)) %>%
    select(outcome, sexprior_pval,
           female_nevents, female_prior_hr_ci, female_prior_pval,
           male_nevents, male_prior_hr_ci, male_prior_pval) %>%
    write_tsv(file = "cabg_sex_priorCABG.tsv")
```

# Outcome CABG

```{r outcome cabg}
dset.nevents <- dset %>%
    map(~filter(., prior == "I9_CABG")) %>%
    map(~select(., -prior)) %>%
    reduce(left_join, by = "outcome") %>%
    select(prior = outcome, female_nevents, male_nevents)

dset %>%
    map(~filter(., outcome == "I9_CABG")) %>%
    map(~select(., -outcome)) %>%
    reduce(left_join, by = "prior") %>%
    select(-female_nevents, -male_nevents) %>%
    left_join(., dset.nevents, by = "prior") %>%
    arrange(sexprior_pval) %>%
    filter(sexprior_pval < 0.05/1384,
           female_prior_hr > 2*male_prior_hr | male_prior_hr > 2*female_prior_hr) %>%
    mutate_at(vars(ends_with("pval")), ~sprintf("%.1E", .x)) %>%
    mutate(female_nevents = sprintf("%s/%s", female_nindivs_prior_outcome, female_nevents),
           male_nevents = sprintf("%s/%s", male_nindivs_prior_outcome, male_nevents)) %>%
    select(-(ends_with("_nindivs_prior_outcome"))) %>%
    select(prior, sexprior_pval,
           female_nevents, female_prior_hr_ci, female_prior_pval,
           male_nevents, male_prior_hr_ci, male_prior_pval) %>%
    write_tsv(file = "cabg_sex_outcomeCABG.tsv")
```

